version: "3"

dotenv: [".env"]

env:
  TMPDIR: ./tmp
  TASK_TEMP_DIR: "{{.TMPDIR}}/.task"
  MIGRATIONS_DIR: "{{.TMPDIR}}/migrations"
  BACKUPS_DIR: "{{.TMPDIR}}/backups"
  GO: "CGO_ENABLED=0 go"

tasks:
  setup:
    desc: "Setup the project"
    cmds:
      - mkdir -p {{.TMPDIR}}
      - mkdir -p {{.MIGRATIONS_DIR}}
      - mkdir -p {{.BACKUPS_DIR}}

  status:
    desc: "Get the status of the database"
    cmds:
      - CGO_ENABLED=0 go run main.go status

  test:
    desc: "Run the tests"
    cmds:
      - CGO_ENABLED=0 go test -coverprofile={{.TMPDIR}}/cover.out ./...

  push-coverage:
    desc: "Push the coverage to Codacy"
    cmds:
      - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r {{.TMPDIR}}/cover.out

  semver:
    desc: "Generate a new semver version"
    cmds:
      - semver-generator -c ./semver.yaml generate -l | awk '{print $2}'

  semver-install:
    desc: "Install the semver-generator"
    cmds:
      - CGO_ENABLED=0 go install github.com/lukaszraczylo/semver-generator@latest

  build:
    desc: "Build the project"
    cmds:
      - CGO_ENABLED=0 go build -o {{.TMPDIR}}/db-kit main.go

  release:
    desc: "Release the project (interactive)"
    deps: [build, test]
    cmds:
      - ./scripts/release.sh

  migrate-new:
    desc: "Create a new migration"
    cmds:
      - CGO_ENABLED=0 go run main.go --user {{.POSTGRES_USER}} --password {{.POSTGRES_PASSWORD}} --db {{.POSTGRES_DB}} --migrations {{.MIGRATIONS_DIR}} migrate create {{.CLI_ARGS}}

  migrate-up:
    desc: "Migrate the database up"
    cmds:
      - CGO_ENABLED=0 go run main.go --user {{.POSTGRES_USER}} --password {{.POSTGRES_PASSWORD}} --db {{.POSTGRES_DB}} --migrations {{.MIGRATIONS_DIR}} migrate up

  migrate-reset:
    desc: "Reset the database"
    cmds:
      - CGO_ENABLED=0 go run main.go --user {{.POSTGRES_USER}} --password {{.POSTGRES_PASSWORD}} --db {{.POSTGRES_DB}} --migrations {{.MIGRATIONS_DIR}} migrate reset

  migrate-down:
    desc: "Migrate the database down"
    cmds:
      - CGO_ENABLED=0 go run main.go --user {{.POSTGRES_USER}} --password {{.POSTGRES_PASSWORD}} --db {{.POSTGRES_DB}} --migrations {{.MIGRATIONS_DIR}} migrate down
