name: Go Build and Test

on:
  push:
    branches:
      - "**"

jobs:
  test-and-coverage:
    name: Test and Upload Coverage to Codacy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.21"
          check-latest: true

      - name: Verify dependencies
        run: go mod verify

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: "3.40.0"

      - name: Build
        run: task setup && task build

      - name: Test and Generate Coverage Report
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          task push-coverage
