name: Release

# Set minimal permissions for security
permissions:
  contents: read

on:
    release:
        types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.21'

    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build
      run: |
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o fileb-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload Artifact to Release
      uses: actions/upload-artifact@v4
      with:
        name: fileb-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./fileb-${{ matrix.goos }}-${{ matrix.goarch }}
